# Generated by Django 4.2.4 on 2023-09-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_prices', to='products.product', verbose_name='Product'),
        ),
    ]
