# Generated by Django 4.2.4 on 2023-09-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_image_image_alter_image_product'),
        ('products', '0003_alter_category_slug'),
    ]

    operations = [
    ]
