# Generated by Django 4.2.4 on 2023-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default image?'),
        ),
    ]
